plugins {
    id 'com.android.application'
}

android {
    namespace 'com.evertoncoraca.mp3player'
    compileSdk 36

    defaultConfig {
        applicationId 'com.evertoncoraca.mp3player'
        minSdk 26
        targetSdk 36
        versionCode 4
        versionName '1.4.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.documentfile:documentfile:1.1.0'
    implementation 'androidx.media3:media3-exoplayer:1.11.1'
    implementation 'androidx.media3:media3-session:1.11.1'

    testImplementation 'junit:junit:4.13.2'
}
